package com.dominus.dominus;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Link;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SignUpViewDesign extends CssLayout {
	protected TextField email;
	protected TextField password;
	protected TextField confirmpass;
	protected TextField lastName;
	protected OptionGroup query;
	protected CheckBox checkAgree;
	protected Link linkTerms;
	protected Button submit;
	protected Button cancel;

	public SignUpViewDesign() {
		Design.read(this);
	}
}
